services:
  floci-ui:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/frontend/src:/app/src
      - ./packages/frontend/index.html:/app/index.html
      - ./packages/frontend/vite.config.ts:/app/vite.config.ts
      - ./packages/frontend/tsconfig.json:/app/tsconfig.json
      - ./packages/frontend/tsconfig.node.json:/app/tsconfig.node.json
    ports:
      - "4500:4500"
    environment:
      API_TARGET: http://floci-api:4501
      VITE_USE_POLLING: "true"
      FLOCI_DEFAULT_REGION: "swedencentral"
    depends_on:
      - floci-api
    restart: unless-stopped
    networks:
      - floci_default

  floci-api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/api/src:/app/src
    ports:
      - "4501:4501"
    environment:
      # Custom env-variable from our Azure-only change
      FLOCI_ENABLED_CLOUDS: azure

      # Floci AZ
      FLOCI_AZURE_ENDPOINT: http://floci-az:4577
      FLOCI_AZURE_ACCOUNT_NAME: devstoreaccount1

      PORT: "4501"

    restart: unless-stopped
    networks:
      - floci_default

networks:
  floci_default:
    name: floci_default
    # Floci AZ owns its own Compose project; both projects join this shared network.
    external: true
