import type {CapabilitySchema, FieldSchema, ResourceActionName, ServiceSchema, TableColumnSchema} from './types'

const sagemakerResourceActions: CapabilitySchema<ResourceActionName>[] = [
    {name: 'list', label: 'List SageMaker AI resources', enabled: true, status: 'available', runtimeRequired: true},
    {name: 'create', label: 'Create SageMaker AI resource', enabled: true, status: 'available', runtimeRequired: true},
    {name: 'delete', label: 'Delete SageMaker AI resource', enabled: true, status: 'available', runtimeRequired: true},
    {name: 'inspect', label: 'Inspect SageMaker AI resource', enabled: true, status: 'available', runtimeRequired: true},
    {
        name: 'update',
        label: 'Update endpoint',
        enabled: false,
        status: 'coming_soon',
        reason: 'Floci supports UpdateEndpoint, but the generic Cloud Explorer update form supports only one resource shape at a time.',
        runtimeRequired: true,
    },
    {
        name: 'stop',
        label: 'Stop training job',
        enabled: false,
        status: 'coming_soon',
        reason: 'Floci supports StopTrainingJob, but the generic resource action route is not wired for lifecycle verbs yet.',
        runtimeRequired: true,
    },
    {
        name: 'invoke',
        label: 'Invoke endpoint',
        enabled: false,
        status: 'coming_soon',
        reason: 'Floci exposes SageMaker AI Runtime invocations, but the generic invoke panel is currently Lambda-specific.',
        runtimeRequired: true,
    },
    {
        name: 'updateTags',
        label: 'Manage tags',
        enabled: false,
        status: 'coming_soon',
        reason: 'Floci supports AddTags, ListTags, and DeleteTags, but the Cloud Explorer tag editor is not generic yet.',
        runtimeRequired: true,
    },
]

const fields: FieldSchema[] = [
    {
        name: 'resourceType',
        label: 'Resource Type',
        type: 'select',
        required: true,
        defaultValue: 'model',
        description: 'Choose which SageMaker AI API create operation to call.',
        options: [
            {label: 'Model', value: 'model'},
            {label: 'Endpoint config', value: 'endpoint-config'},
            {label: 'Endpoint', value: 'endpoint'},
            {label: 'Training job', value: 'training-job'},
        ],
    },
    {
        name: 'modelName',
        label: 'Model Name',
        type: 'text',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'model'},
        visibleWhen: {field: 'resourceType', equals: 'model'},
        group: 'Model',
        description: 'Required when Resource Type is Model.',
    },
    {
        name: 'executionRoleArn',
        label: 'Execution Role ARN',
        type: 'text',
        required: false,
        visibleWhen: {field: 'resourceType', equals: 'model'},
        group: 'Model',
        description: 'Optional for Floci, but most SDK examples include one.',
    },
    {
        name: 'primaryContainer',
        label: 'Primary Container JSON',
        type: 'textarea',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'model'},
        visibleWhen: {field: 'resourceType', equals: 'model'},
        group: 'Model',
        span: true,
        defaultValue: '{"Image":"example-image"}',
        description: 'CreateModel PrimaryContainer as JSON, for example {"Image":"my-image","ModelDataUrl":"s3://bucket/model.tar.gz"}.',
    },
    {
        name: 'endpointConfigName',
        label: 'Endpoint Config Name',
        type: 'text',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'endpoint-config'},
        visibleWhen: {field: 'resourceType', equals: 'endpoint-config'},
        group: 'Endpoint config',
        description: 'Required when Resource Type is Endpoint config.',
    },
    {
        name: 'productionVariants',
        label: 'Production Variants JSON',
        type: 'textarea',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'endpoint-config'},
        visibleWhen: {field: 'resourceType', equals: 'endpoint-config'},
        group: 'Endpoint config',
        span: true,
        defaultValue: '[{"VariantName":"AllTraffic","ModelName":"model-name","InitialInstanceCount":1,"InstanceType":"ml.t2.medium"}]',
        description: 'CreateEndpointConfig ProductionVariants array as JSON.',
    },
    {
        name: 'endpointName',
        label: 'Endpoint Name',
        type: 'text',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'endpoint'},
        visibleWhen: {field: 'resourceType', equals: 'endpoint'},
        group: 'Endpoint',
        description: 'Required when Resource Type is Endpoint.',
    },
    {
        name: 'endpointConfigNameForEndpoint',
        label: 'Endpoint Config Name',
        type: 'text',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'endpoint'},
        visibleWhen: {field: 'resourceType', equals: 'endpoint'},
        group: 'Endpoint',
        description: 'Existing endpoint config to attach to the endpoint.',
    },
    {
        name: 'trainingJobName',
        label: 'Training Job Name',
        type: 'text',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'training-job'},
        visibleWhen: {field: 'resourceType', equals: 'training-job'},
        group: 'Training job',
        description: 'Required when Resource Type is Training job.',
    },
    {
        name: 'algorithmSpecification',
        label: 'Algorithm Specification JSON',
        type: 'textarea',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'training-job'},
        visibleWhen: {field: 'resourceType', equals: 'training-job'},
        group: 'Training job',
        span: true,
        defaultValue: '{"TrainingImage":"example-image","TrainingInputMode":"File"}',
        description: 'CreateTrainingJob AlgorithmSpecification as JSON.',
    },
    {
        name: 'roleArn',
        label: 'Role ARN',
        type: 'text',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'training-job'},
        visibleWhen: {field: 'resourceType', equals: 'training-job'},
        group: 'Training job',
    },
    {
        name: 'outputDataConfig',
        label: 'Output Data Config JSON',
        type: 'textarea',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'training-job'},
        visibleWhen: {field: 'resourceType', equals: 'training-job'},
        group: 'Training job',
        span: true,
        defaultValue: '{"S3OutputPath":"s3://bucket/output"}',
    },
    {
        name: 'resourceConfig',
        label: 'Resource Config JSON',
        type: 'textarea',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'training-job'},
        visibleWhen: {field: 'resourceType', equals: 'training-job'},
        group: 'Training job',
        span: true,
        defaultValue: '{"InstanceType":"ml.m5.large","InstanceCount":1,"VolumeSizeInGB":1}',
    },
    {
        name: 'stoppingCondition',
        label: 'Stopping Condition JSON',
        type: 'textarea',
        required: false,
        requiredWhen: {field: 'resourceType', equals: 'training-job'},
        visibleWhen: {field: 'resourceType', equals: 'training-job'},
        group: 'Training job',
        span: true,
        defaultValue: '{"MaxRuntimeInSeconds":3600}',
    },
    {
        name: 'inputDataConfig',
        label: 'Input Data Config JSON',
        type: 'textarea',
        required: false,
        visibleWhen: {field: 'resourceType', equals: 'training-job'},
        group: 'Training job',
        span: true,
        description: 'Optional CreateTrainingJob InputDataConfig array as JSON.',
    },
]

const columns: TableColumnSchema[] = [
    {name: 'name', label: 'Name'},
    {name: 'kind', label: 'Kind', path: 'metadata.kind', format: 'badge'},
    {name: 'status', label: 'Status', format: 'badge', emptyText: '—'},
    {name: 'createdAt', label: 'Created', format: 'relative', emptyText: '—'},
    {name: 'arn', label: 'ARN', path: 'metadata.arn', emptyText: '—'},
]

export function awsSageMakerSchema(): ServiceSchema {
    return {
        cloud: 'aws',
        service: 'sagemaker',
        displayName: 'SageMaker AI',
        fields,
        actions: ['list', 'create', 'delete', 'inspect'],
        capabilities: {resourceActions: sagemakerResourceActions},
        filters: [{name: 'search', label: 'Search', type: 'text', required: false}],
        columns,
    }
}
